name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the latest minor version of Python 3

    - name: Run Python Script
      run: |
        python "Git Log.py"  # Enclose the filename in quotes
